#! /bin/csh -f

set msglvl  = 1
set msgFile = stdout
set msgFile = res


set type    =   1
set type    =   2

set nrow    = 2000
set ncol    =  40
# column major
set inc1    =  1
set inc2    = $nrow
# row major
set inc1    = $ncol
set inc2    =  1
set seed    = 1010101
set nproc   = 4

#
#  for solaris with mpich
#
set pgFile  = gather$nproc.pg
/usr/local/mpi/bin/mpirun -p4pg $pgFile \
testGather \
   $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed
 
#
#  for sgi
#
# mpirun -np $nproc \
# testGather \
#    $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed
 
#
#  for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
# testGather \
#    $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed

