#! /bin/csh -f

set msglvl  = 1
set msgFile = stdout
set msgFile = res


set type  = 3
set nvtx  = 1000
set nitem = 5000
set root  = 1

set seed  = 10101
set nproc = 4

#
#  for solaris with mpich
#
set pgFile  = Graph_Bcast$nproc.pg
# /usr/local/mpi/bin/mpirun -p4pg $pgFile \
/usr/local/mpich-1.0.13/bin/mpirun -p4pg $pgFile \
   testGraph_Bcast $msglvl $msgFile $type $nvtx $nitem $root $seed
 
#
#  for sgi
#
# mpirun -np $nproc \
#  testGraph_Bcast $msglvl $msgFile $type $nvtx $nitem $root $seed
 
#
#  for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
#  testGraph_Bcast $msglvl $msgFile $type $nvtx $nitem $root $seed
