#! /bin/csh -f

set msglvl  = 1
set msgFile = stdout
set msgFile = res


set type    =   1
set type    =   2

set nrow    = 100
set ncol    =  4
set inc1    =  1
set inc2    = $nrow
set inc1    = $ncol
set inc2    =  1
set seed    = 10101
set nproc   = 4
set root    = 1

#
#  for solaris with mpich
#
set pgFile  = scatterDenseMtx$nproc.pg
/usr/local/mpi/bin/mpirun -p4pg $pgFile \
testScatterDenseMtx \
   $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed $root
 
#
#  for sgi
#
# mpirun -np $nproc \
# testScatterDenseMtx \
#    $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed $root
 
#
#  for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
# testScatterDenseMtx \
#    $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed $root

