all_drivers :
	

lib :
	cd srcST  ; make Bridge.a
	cd srcMT  ; make BridgeMT.a
	cd srcMPI ; make BridgeMPI.a

clean :
	cd srcST   ; make clean
	cd srcMT   ; make clean
	cd srcMPI  ; make clean
	cd doc     ; make clean
	cd drivers ; make clean
