#! /bin/csh -f

set MTX_DIR = /home/pattersn/LANCZOS/test/inp

set pgFile = spooles.pg

echo matrix4

uncompress < $MTX_DIR/matrix.4A.Z > fort.37
uncompress < $MTX_DIR/matrix.4B.Z > fort.38

set msglvl   = 0
set msgFile  = res.mtx4
set parmFile = mtx4.inp
set seed     = 10
set inFileA  = fort.37
set inFileB  = fort.38
set resFile  = res.mtx4

/usr/local/mpi/bin/mpirun -p4pg $pgFile \
testMPI $msglvl $msgFile $parmFile $seed $inFileA $inFileB 

rm fort.* lmq* lq* evc* res.9*
