#! /bin/csh -f

set MTX_DIR = /home/pattersn/LANCZOS/test/inp

echo matrix3

uncompress < $MTX_DIR/matrix.3A.Z > fort.37
uncompress < $MTX_DIR/matrix.3B.Z > fort.38

set msglvl   = 0
set msgFile  = res.mtx3
set parmFile = mtx3.inp
set seed     = 10
set inFileA  = fort.37
set inFileB  = fort.38
set resFile  = res.mtx3

set nthread = 4

testMT $msglvl $msgFile $parmFile $seed $nthread $inFileA $inFileB 

rm fort.* lmq* lq* evc*
