#! /bin/csh -f

set MTX_DIR = /home/pattersn/LANCZOS/test/inp

echo matrix7

uncompress < $MTX_DIR/matrix.7A.Z > fort.37
uncompress < $MTX_DIR/matrix.7B.Z > fort.38

set msglvl   = 0
set msgFile  = res.mtx7
set parmFile = mtx7.inp
set seed     = 10
set inFileA  = fort.37
set inFileB  = fort.38
set resFile  = res.mtx7

testSerial $msglvl $msgFile $parmFile $seed $inFileA $inFileB 

rm fort.* lmq* lq* evc*
