#! /bin/csh -f

set matrices     = ../../Matrices
set matrix       = R2D100
set inETreeFile = $matrices/$matrix/nd.etreef
set inGraphFile = $matrices/$matrix/orig0.graphf

set matrices     = ../../../matrices
set matrix       = GRD31x31x31
set matrix       = BCSSTK24
set matrix       = BCSSTK30
set matrix       = GRD15x15x127
set inETreeFile = $matrices/$matrix/nd2.etreef
set inETreeFile = $matrices/$matrix/best0.etreef
set inETreeFile = $matrices/$matrix/msmd.etreef
set inETreeFile = $matrices/$matrix/mmd.etreef
set inETreeFile = $matrices/$matrix/nd.etreef
set inETreeFile = $matrices/$matrix/ms.etreef

set inGraphFile = $matrices/$matrix/orig1.graphb
set inGraphFile = $matrices/$matrix/orig0.graphb

set msglvl  = 1
set msgFile = stdout

testStorage $msglvl $msgFile $inETreeFile $inGraphFile 
