#! /bin/csh -f
#
 
set msglvl       =       1
set msgFile      =     res 
set msgFile      =  stdout
set type         =       2
set symflag      =       1
set nD           =       6
set nU           =       5
set seed         =     7777

test_swap \
   $msglvl $msgFile $nD $nU $type $symflag $seed
