#! /bin/csh -f

set msglvl           = 1
set msgFile          = res3D.64
set msgFile          = res3D
set msgFile          = stdout
set msgFile          = res

set n1       =    7
set n2       =    7
set n3       =    7
set maxzeros =    0
set maxzeros = 1000
set maxsize  = 1000
set maxsize  =   64

set seed             = 10101
set type             = 1
set symmetryflag     = 2
set sparsityflag     = 0
set pivotingflag     = 0
set tau              = 10
set droptol          = 1.e-50
set randomFlag       = 1
set nrhs             = 4
set profile          = 0
set nproc            = 4
set maptype          = 3
set cutoff           = 0.125
set lookahead        = 0

#
#  for solaris with mpich
#
set pgFile = gridMPI$nproc.pg
/usr/local/mpi/bin/mpirun -p4pg $pgFile \
testGridMPI \
   $msglvl $msgFile $n1 $n2 $n3 $maxzeros $maxsize $seed \
   $type $symmetryflag $sparsityflag $pivotingflag $tau $droptol \
   $lookahead $nrhs $maptype $cutoff
 
#
# for sgi
#
# mpirun -np $nproc \
# testGridMPI \
#    $msglvl $msgFile $n1 $n2 $n3 $maxzeros $maxsize $seed \
#    $type $symmetryflag $sparsityflag $pivotingflag $tau $droptol \
#    $lookahead $nrhs $maptype $cutoff
 
 
#
# for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
# testGridMPI \
#    $msglvl $msgFile $n1 $n2 $n3 $maxzeros $maxsize $seed \
#    $type $symmetryflag $sparsityflag $pivotingflag $tau $droptol \
#    $lookahead $nrhs $maptype $cutoff

