#! /bin/csh -f

set msglvl  = 1
set msgFile = stdout
set msgFile = res


set n     = 10000
set seed  = 10101
set nproc = 8

#
#  for solaris with mpich
#
set pgFile  = IVallgather$nproc.pg
# /usr/local/mpi/bin/mpirun -p4pg $pgFile \
/usr/local/mpich-1.0.13/bin/mpirun -p4pg $pgFile \
   testIVallgather $msglvl $msgFile $n $seed
 
#
#  for sgi
#
# mpirun -np $nproc \
# testIVallgather $msglvl $msgFile $n $seed
 
#
#  for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
# testIVallgather $msglvl $msgFile $n $seed

