#! /bin/csh -f

set msglvl  = 1
set msgFile = stdout
set msgFile = res


set nlist       = 1000
set maxlistsize = 200
set root        = 1

set seed  = 10101
set nproc = 4

#
#  for solaris with mpich
#
set pgFile  = IVL_Bcast$nproc.pg
# /usr/local/mpi/bin/mpirun -p4pg $pgFile \
/usr/local/mpich-1.0.13/bin/mpirun -p4pg $pgFile \
   testIVL_Bcast $msglvl $msgFile $nlist $maxlistsize $root $seed
 
#
#  for sgi
#
# mpirun -np $nproc \
#  testIVL_Bcast $msglvl $msgFile $nlist $maxlistsize $root $seed
 
#
#  for hp
#
# /opt/mpi/bin/mpirun -np $nproc \
#  testIVL_Bcast $msglvl $msgFile $nlist $maxlistsize $root $seed

