#! /bin/csh -f

set matrices     = ../../Matrices
set matrix       = R2D100

set inFile = $matrices/$matrix/orig.egraphf

set outFile = $matrices/$matrix/orig.egraphb
set outFile = none

set msglvl  = 3

set msgFile = stdout

testIO $msglvl $msgFile $inFile $outFile
