#! /bin/csh -f
#
set msglvl  = 2
set msgFile = stdout
set type    = 2
set nrow    = 10
set ncol    = 20
set inc1    = $ncol
set inc1    = 1
set inc2    = 1
set inc2    = $nrow
set seed    = 1
test_norms $msglvl $msgFile $type $nrow $ncol $inc1 $inc2 $seed
