#! /bin/csh -f

set msglvl        = 2
set msgFile       = stdout
set n1            = 7
set n2            = 7

set matrices      = ../../Matrices
set matrix        = GRD7x7
set inCoordsFile  = none
set inCoordsFile  = $matrices/$matrix/$matrix.coordsb
set inCoordsFile  = $matrices/$matrix/$matrix.coordsf
set outCoordsFile = $matrices/$matrix/$matrix.coordsf
set outCoordsFile = $matrices/$matrix/$matrix.coordsb
set outCoordsFile = none

testIO $msglvl $msgFile $inCoordsFile $outCoordsFile
