#! /bin/csh -f

set msglvl  = 1
set msgFile = res
set msgFile = stdout

set target   = IV
set sortType = QU
set n        = 100
set nrange   = 9999999
set mod      = 9999999
set seed     = 10101

foreach target ( IV IV2 IVDV IV2DV IVZV IV2ZV DV DVIV DV2 )
#  foreach sortType ( IU ID QU QD )
   foreach sortType ( QU QD )
      test_sort $msglvl $msgFile $target $sortType $n $nrange $mod $seed
   end
end
