#! /bin/csh -f

set matrices     = ../../Matrices
set matrix       = R2D100

set inFile  = $matrices/$matrix/gem.permf

set outFile = $matrices/$matrix/gem.permb
set outFile = none

set msglvl  = 3

set msgFile = stdout

testIO $msglvl $msgFile $inFile $outFile
