#! /bin/csh -f

set MTX_DIR = /home/pattersn/LANCZOS/test/inp

echo matrix10

uncompress < $MTX_DIR/matrix.10A.Z > fort.37
uncompress < $MTX_DIR/matrix.10B.Z > fort.38

set msglvl   = 0
set msgFile  = res.mtx10
set parmFile = mtx10.inp
set seed     = 10
set inFileA  = fort.37
set inFileB  = fort.38
set resFile  = res.mtx10

set nthread  = 4

testMT $msglvl $msgFile $parmFile $seed $nthread $inFileA $inFileB 

rm fort.* lmq* lq* evc*
