#! /bin/csh -f

set matrices    = ../../Matrices
set matrix      = R2D100
set inGraphFile = $matrices/$matrix/orig0.graphf

set matrix      = R2D10000
set inGraphFile = $matrices/$matrix/orig1.graphf
set inGraphFile = $matrices/$matrix/orig0.graphf

set matrix      = BCSSTK16
set inGraphFile = $matrices/$matrix/orig1.graphb

set matrices    = ../../../matrices
set matrix      = BCSSTK39
set inGraphFile = $matrices/$matrix/orig1.graphb

set msglvl      = 1

set msgFile    = res2
set msgFile    = res.$matrix
set msgFile    = stdout

set compressFlag = 2
set prioType     = 1
set stepType     = 1

set nseed      = 11
set nseed      = 11
set nseed      = 21
set nseed      =  4
set nseed      = 1

set frontTreeFile = temp.etreef
set frontTreeFile = none
set frontTreeFile = $matrices/$matrix/mmd.etreef

set oldToNewIVfile = $matrices/$matrix/mmdOldToNew.ivf
set oldToNewIVfile = temp.ivf
set oldToNewIVfile = none

set newToOldIVfile = $matrices/$matrix/newToOld.ivf
set newToOldIVfile = none

#  @ seed = $nseed
   @ seed = 1
   while ( $seed <= $nseed )
      echo ' seed = ' $seed
      orderViaMMD $msglvl $msgFile $inGraphFile \
              $seed $compressFlag $prioType $stepType \
              $frontTreeFile $oldToNewIVfile $newToOldIVfile 
      @ seed = $seed + 1
   end
